version: "2"
services:
  app:
    image: noaavisrur/compose-flask:latest
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/jenkins/workspace/docker_compose_flask/flask-project/flask+DB/db:/docker-entrypoint-initdb.d/:ro
