version: "2"
services:
  app:
    image: noaavisrur/flask-compose:latest
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: noaavisrur/mysql-compose:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/ec2-user/flask-compose-dir:/docker-entrypoint-initdb.d/:ro
