apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: flask-cluster
  region: us-east-2
nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    availabilityZones:
      - us-east-2a
      - us-east-2b
      - us-east-2c
