apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-compose-container
          image: noaavisrur/flask-compose:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PORT
              value: "3306"
          # Add additional configurations for the Flask container

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-compose-container
  template:
    metadata:
      labels:
        app: mysql-compose-container
    spec:
      containers:
        - name: mysql-compose-container
          image: noaavisrur/mysql-compose:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          # Add additional configurations for the MySQL container

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql-compose-container
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
