apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-compose-container
          image: noaavisrur/flask-compose:latest
          ports:
            - containerPort: 5000
        - name: mysql-compose-container
          image: noaavisrur/mysql-compose:latest
          # Add additional configurations for the database container

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
